import type { Metadata } from "next";
import { Exo, Oxygen } from "next/font/google";

import "./styles/globals.css";

const oxygen = Oxygen({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-oxygen",
});

const exo = Exo({
  subsets: ["latin"],
  variable: "--font-exo",
})

export const metadata: Metadata = {
  title: "e-commerce-start-up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oxygen.variable} ${exo.variable} font-sans antialiased selection:bg-primary/95 selection:text-primary-foreground`}
      >
        {children}
      </body>
    </html>
  );
}
